### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by frozenspider** [deathtracktor/audioknigi-club-downloader-app#1]
This app used to work well, but it seem that developers deliberately changed something on the website backend. Now it does this:
```
E:\ProgramFiles\audioknigi-club-downloader-app\dist> app https://audioknigi.club/glubina-1
Downloading chapter Слушаем на сайте Audioknigi.club
Downloading chapter Слушаем на сайте Audioknigi.club
Downloading chapter Слушаем на сайте Audioknigi.club
Downloading chapter Слушаем на сайте Audioknigi.club
Downloading chapter Слушаем на сайте Audioknigi.club
All done.
```
Here's the file: [Слушаем на сайте Audioknigi.club.zip](https://github.com/deathtracktor/audioknigi-club-downloader-app/files/2322031/Audioknigi.club.zip)

**Comment by deathtracktor** [comment]
Looks like these guys implemented signature check for `ajax/bid` endpoint. I will look at it.

**Comment by deathtracktor** [comment]
[Fixed](https://github.com/deathtracktor/audioknigi-club-downloader-app/commit/d69be73a6b43d6b8e69f4ca1584d3ebb109e8f00)
