### ISSUE TITLE
--onefile does not work

### ISSUE THREAD

**Issue by tpaktop77** [deathtracktor/audioknigi-club-downloader-app#5]
> $ python app.py https://audioknigi.club/martynov-georgiy-spiral-vremeni --onefile
> Usage: app.py [OPTIONS] AUDIO_BOOK_URL
> Try "app.py -h" for help.
> 
> Error: no such option: --onefile

> $ grep -ri  onefile ./
> .//README.md:pyinstaller app.spec --onefile

**Comment by tpaktop77** [comment]
Oh, my excuses, I thought it's script option, to write single mp3 file.

**Comment by deathtracktor** [comment]
No problemo!

:)
